added some useful validators
vapor/validation pull request #11
Opened 2017-07-17 02:47 UTC by Charliekenney23

Just thought I'd add some things that I used in a side project to get to know vapor. Let me know if I need to change anything

2017-07-19 20:10 UTC, tanner0101 requested changes

2017-07-19 20:10 UTC, tanner0101 commented on Tests/ValidationTests/ValidationTests.swift
> +
there should be a `static let allTests` somewhere in this doc. can you add these tests to it? (without that, they won't run on linux). thanks!

2017-07-20 00:09 UTC, Charliekenney23 commented
Yikes... added the email validation (not my commit) tests to the test array and its failing, gonna try to figure out why and revert.

2017-07-20 01:26 UTC, Charliekenney23 commented
It passed 😅. Really enjoying the Vapor, and I'd like to help out in anyway possible. I know you guys are busy with documentation and such for 2.0, so if its wanted, I'm happy to add a lot more validators and refactor some of the current ones. Let me know

2017-07-20 18:19 UTC, tanner0101 approved these changes

2017-07-20 18:19 UTC, tanner0101 commented
Thanks @Charliekenney23! Any documentation you'd like to submit regarding validation would be greatly appreciated https://github.com/vapor/documentation

2017-07-20 18:19 UTC, merged